Usability improvements and fixes
Synthetixio/hardhat-interact pull request #1
Opened 2022-03-21 05:13 UTC by artdgn

Changes:
- fix handling of array outputs in queries
- fix handling of struct outputs in queries
- make autocomplete use substrings instead of prefix: e.g. `btc` will match all things containing BTC (but also De**btC**ache). 
- add instructions for local development
- bump patch version

-------------
Examples:

Fix arrays (this would previously crash):
![image](https://user-images.githubusercontent.com/29574203/159208410-cf70bb16-1ceb-444e-a586-3b2d1be6a2aa.png)

Fix structs (this would previously crash):
![image](https://user-images.githubusercontent.com/29574203/159208384-f69d9034-5ca4-49ac-a74f-0ea99cf7cc30.png)

Autocomplete improvement:
![image](https://user-images.githubusercontent.com/29574203/159208286-5920a059-eeeb-4b9b-b6e2-2b21d9e6156c.png)

2022-03-21 14:48 UTC, dbeal-eth requested changes

2022-03-21 14:48 UTC, dbeal-eth commented on README.md
> +2. in one terminal run `npm run watch` to build on changes
`npm run watch` may not be a valid command on all projects, if I'm not mistaken it has to be defined

2022-03-21 14:48 UTC, dbeal-eth commented on package.json
> +  "version": "0.2.1",
this should only be done when the package is ready for update by whoever runs `npm publish`

2022-03-21 14:48 UTC, dbeal-eth commented on src/interact.ts
> +            suggest: suggestBySubtring
👏

2022-03-21 14:48 UTC, dbeal-eth commented on src/interact.ts
> +        return value.map(item => printReturnedValue(output.arrayChildren, item)).join(', ');
np it would be a little better if the output was displayed like `0x000000, 0x000001, 0x00002) (sBTC, sETH, sUSD)` instead of `0x00000 (sBTC), 0x0000001 (sETH), 0x00000002 (sUSD)` (see the example you shared in your PR changes comment)

2022-03-21 14:48 UTC, dbeal-eth commented on src/interact.ts
> +Promise.resolve(choices.filter(choice => {
np could probably just use an `async` function (you wouldn't need any awaits and less typing)

2022-03-21 16:17 UTC, barrasso approved these changes

2022-03-21 21:54 UTC, artdgn commented on README.md
> +2. in one terminal run `npm run watch` to build on changes
this part of the instructions is for this project, where it exists.

2022-03-21 21:54 UTC, artdgn commented on package.json
> +  "version": "0.2.1",
will remove

2022-03-21 21:56 UTC, artdgn commented on src/interact.ts
> +        return value.map(item => printReturnedValue(output.arrayChildren, item)).join(', ');
don't see how I can make this work for nesting (e.g. array of structs of arrays of structs ...)

2022-03-21 21:57 UTC, artdgn commented on src/interact.ts
> +Promise.resolve(choices.filter(choice => {
yeah makes sense, I just adapted the code pasted from the `promts` package docs :sweat_smile:

2022-03-24 23:28 UTC, dbeal-eth approved these changes

2022-03-24 23:28 UTC, dbeal-eth commented on src/interact.ts
> +        return value.map(item => printReturnedValue(output.arrayChildren, item)).join(', ');
yes

2022-03-24 23:28 UTC, dbeal-eth commented on src/interact.ts
> +        return value.map(item => printReturnedValue(output.arrayChildren, item)).join(', ');
this can be improved in future pr

2022-04-01 04:39 UTC, merged